---
- name: Restart munge
  ansible.builtin.systemd:
    name: munge
    state: restarted

- name: Restart slurmdbd
  ansible.builtin.systemd:
    name: slurmdbd
    state: restarted

- name: Restart slurmctld
  ansible.builtin.systemd:
    name: slurmctld
    state: restarted
